// можна замінити на generated by prisma

export type Priority = 'low' | 'medium' | 'high';
export type ItemStatus = 'free' | 'reserved';

export interface User {
  id: string;
  email: string;
  fullName: string;
  description: string | null;
  isActive: boolean;
  createdAt: string;
}

export interface AuthResponse {
  user: User;
  token: string;
}

export interface Wishlist {
  id: string;
  userId: string;
  title: string;
  description: string | null;
  occasion: string | null;
  isPublic: boolean;
  eventDate: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface WishlistListItem extends Wishlist {
  _count?: { wishItems: number };
}

export interface Reservation {
  id: string;
  wishItemId: string;
  reserverId: string | null;
  reserverName: string | null;
  note: string | null;
  isAnonymous: boolean;
  createdAt: string;
}

export interface WishItem {
  id: string;
  wishlistId: string;
  title: string;
  description: string | null;
  url: string | null;
  imageUrl: string | null;
  price: string | number | null;
  currency: string;
  priority: Priority;
  status: ItemStatus;
  createdAt: string;
  updatedAt: string;
  reservation: Reservation | null;
}

export interface WishlistDetails extends Wishlist {
  user: Pick<User, 'id' | 'fullName' | 'email'>;
  wishItems: WishItem[];
}


export interface RegisterInput {
  email: string;
  password: string;
  fullName: string;
}

export interface LoginInput {
  email: string;
  password: string;
}

export interface CreateWishlistInput {
  title: string;
  description?: string;
  occasion?: string;
  isPublic?: boolean;
  eventDate?: string;
}

export type UpdateWishlistInput = Partial<CreateWishlistInput>;

export interface CreateWishItemInput {
  title: string;
  description?: string;
  url?: string;
  imageUrl?: string;
  price?: number;
  currency?: string;
  priority?: Priority;
}

export type UpdateWishItemInput = Partial<CreateWishItemInput>;

export interface ReserveInput {
  reserverName?: string;
  note?: string;
  isAnonymous?: boolean;
}
